apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiki
  namespace: argocd
spec:
  sources:
  - repoURL: https://charts.js.wiki
    chart: wiki
    targetRevision: x
    helm:
      valueFiles:
        - $values/01_WIKI/values.yaml
  - repoURL: 'https://github.com/Cloud-Computing-2324/deployment-exercises-Tiebevn.git'
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: uptime
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true